name: CI Fuzz

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: app.code-intelligence.com:6773
  WEB_APP_ADDRESS:  https://app.code-intelligence.com
  PROJECT_ID: projects/18482300_github_lighttpd-223f0fe0


jobs:
  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Build and Instrument
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          project: ${{ env.PROJECT_ID }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: report-coverage
        name: Report Coverage
        uses: CodeIntelligenceTesting/github-actions/report-coverage@v3
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: list-findings
        name: List Findings
        uses: CodeIntelligenceTesting/github-actions/list-findings@v3 
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          name: 'CI Fuzz Findings'
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          dashboard_address: ${{env.WEB_APP_ADDRESS}}
          project: ${{env.PROJECT_ID}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          
